### ISSUE TITLE
Documentation dependency `quartodoc` mixed with main dependencies

### ISSUE THREAD

**Issue by ptamarit** [front-matter/commonmeta-py#68]
Hello,

We are using `commonmeta-py` in [`inveniosoftware/invenio-rdm-records`](https://github.com/inveniosoftware/invenio-rdm-records/) and started running into problems with ~~`v0.9.x`~~ _`v0.8.7`_.

The problem is related to the fact that `quartodoc` (a documentation dependency), is listed as a main dependency:
https://github.com/front-matter/commonmeta-py/blob/a610c1c255f24d6095e9e564a55ead866f3753a8/pyproject.toml#L39-L41

The proper way to define such dependencies [according to the Poetry documentation](https://python-poetry.org/docs/managing-dependencies/#optional-groups) is:

```toml
[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
# Docs deps here...
```

Do you think you could release a new version with these dependencies out of the main list?

Thanks,
Pablo
